apiVersion: v1
kind: Service
metadata:
  name: {{ include "phasor-backend.fullname" . }}
  labels:
    {{- include "phasor-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "phasor-backend.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "phasor-backend.fullname" . }}-canary
  labels:
    {{- include "phasor-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "phasor-backend.selectorLabels" . | nindent 4 }}
