{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "phasor-backend.serviceAccountName" . }}
  labels:
    {{- include "phasor-backend.labels" . | nindent 4 }}
{{- end }}
